//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSviewCloud {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_text() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSviewCloud.Resource_text", typeof(Resource_text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncCycleAudio_str {
            get {
                return ResourceManager.GetString("FuncCycleAudio_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncCycleAudio_tip_str {
            get {
                return ResourceManager.GetString("FuncCycleAudio_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncCycleChannel_str {
            get {
                return ResourceManager.GetString("FuncCycleChannel_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncCycleChannel_tip_str {
            get {
                return ResourceManager.GetString("FuncCycleChannel_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncCycleSubtitle_str {
            get {
                return ResourceManager.GetString("FuncCycleSubtitle_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncCycleSubtitle_tip_str {
            get {
                return ResourceManager.GetString("FuncCycleSubtitle_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncForwardChapter_str {
            get {
                return ResourceManager.GetString("FuncForwardChapter_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncForwardChapter_tip_str {
            get {
                return ResourceManager.GetString("FuncForwardChapter_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncPlayExit_str {
            get {
                return ResourceManager.GetString("FuncPlayExit_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncPlayExit_tip_str {
            get {
                return ResourceManager.GetString("FuncPlayExit_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncResizeOriginal_str {
            get {
                return ResourceManager.GetString("FuncResizeOriginal_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncResizeOriginal_tip_str {
            get {
                return ResourceManager.GetString("FuncResizeOriginal_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncRewindChapter_str {
            get {
                return ResourceManager.GetString("FuncRewindChapter_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncRewindChapter_tip_str {
            get {
                return ResourceManager.GetString("FuncRewindChapter_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncSeekMinus10sec_str {
            get {
                return ResourceManager.GetString("FuncSeekMinus10sec_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncSeekMinus10sec_tip_str {
            get {
                return ResourceManager.GetString("FuncSeekMinus10sec_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncSeekMinus60sec_str {
            get {
                return ResourceManager.GetString("FuncSeekMinus60sec_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncSeekMinus60sec_tip_str {
            get {
                return ResourceManager.GetString("FuncSeekMinus60sec_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncSeekPlus10sec_str {
            get {
                return ResourceManager.GetString("FuncSeekPlus10sec_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncSeekPlus10sec_tip_str {
            get {
                return ResourceManager.GetString("FuncSeekPlus10sec_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncSeekPlus60sec_str {
            get {
                return ResourceManager.GetString("FuncSeekPlus60sec_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncSeekPlus60sec_tip_str {
            get {
                return ResourceManager.GetString("FuncSeekPlus60sec_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncSrcAutoVolume_str {
            get {
                return ResourceManager.GetString("FuncSrcAutoVolume_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncSrcAutoVolume_tip_str {
            get {
                return ResourceManager.GetString("FuncSrcAutoVolume_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncSrcVolumeDown_str {
            get {
                return ResourceManager.GetString("FuncSrcVolumeDown_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncSrcVolumeDown_tip_str {
            get {
                return ResourceManager.GetString("FuncSrcVolumeDown_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncSrcVolumeUp_str {
            get {
                return ResourceManager.GetString("FuncSrcVolumeUp_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncSrcVolumeUp_tip_str {
            get {
                return ResourceManager.GetString("FuncSrcVolumeUp_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncToggleDisplay_str {
            get {
                return ResourceManager.GetString("FuncToggleDisplay_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncToggleDisplay_tip_str {
            get {
                return ResourceManager.GetString("FuncToggleDisplay_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncToggleFullscreen_str {
            get {
                return ResourceManager.GetString("FuncToggleFullscreen_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncToggleFullscreen_tip_str {
            get {
                return ResourceManager.GetString("FuncToggleFullscreen_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncToggleMute_str {
            get {
                return ResourceManager.GetString("FuncToggleMute_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncToggleMute_tip_str {
            get {
                return ResourceManager.GetString("FuncToggleMute_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncTogglePause_str {
            get {
                return ResourceManager.GetString("FuncTogglePause_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncTogglePause_tip_str {
            get {
                return ResourceManager.GetString("FuncTogglePause_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncVolumeDown_str {
            get {
                return ResourceManager.GetString("FuncVolumeDown_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncVolumeDown_tip_str {
            get {
                return ResourceManager.GetString("FuncVolumeDown_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncVolumeUp_str {
            get {
                return ResourceManager.GetString("FuncVolumeUp_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncVolumeUp_tip_str {
            get {
                return ResourceManager.GetString("FuncVolumeUp_tip_str", resourceCulture);
            }
        }
    }
}
